// Generated by CoffeeScript 1.4.0
(function() {

  this.Sprite = (function() {

    function Sprite(img, pos, size, speed, frames, horizontal) {
      this.img = img;
      this.pos = pos != null ? pos : [0, 0];
      this.size = size != null ? size : [16, 16];
      this.speed = speed != null ? speed : 0;
      this.frames = frames != null ? frames : [0];
      this.horizontal = horizontal != null ? horizontal : true;
      this._index = 0;
    }

    Sprite.prototype.update = function(dt) {
      return this._index += this.speed * dt;
    };

    Sprite.prototype.paint = function(ctx) {
      var frame, idx, max, x, y;
      max = this.frames.length;
      idx = Math.floor(this._index);
      frame = this.frames[idx % max];
      this._index -= max * Math.floor(this._index / max);
      x = this.pos[0];
      y = this.pos[1];
      if (this.horizontal) {
        x += frame * this.size[0];
      } else {
        y += frame * this.size[1];
      }
      return ctx.drawImage(this.img, x, y, this.size[0], this.size[1], 0, 0, this.size[0], this.size[1]);
    };

    return Sprite;

  })();

}).call(this);
